module Tag (..) where


type Tag
    = AWS
    | Agile
    | Android
    | AngularJS
    | Australia
    | Belarus
    | Belgium
    | BigData
    | Bulgaria
    | CPlusPlus
    | CSS
    | Canada
    | Chef
    | China
    | Clojure
    | Cloud
    | Cocoa
    | Communications
    | Croatia
    | CycleJS
    | CzechRepublic
    | DataVisualization
    | Denmark
    | Designers
    | DevOps
    | Developers
    | Diversity
    | Docker
    | DotNet
    | Drupal
    | Elasticserch
    | Elixir
    | Ember
    | England
    | English
    | Erlang
    | FSharp
    | Finland
    | France
    | French
    | FunctionalProgramming
    | General
    | German
    | Germany
    | Go
    | Gradle
    | Grails
    | Groovy
    | Hadoop
    | Haskell
    | Hungary
    | IOS
    | India
    | InternetOfThings
    | Ireland
    | Italian
    | Italy
    | Japan
    | Japanese
    | Java
    | JavaScript
    | Latvia
    | Lebanon
    | Lisp
    | Lithuania
    | Logstash
    | Mexico
    | Microservices
    | Mobile
    | MongoDB
    | Netherlands
    | NewZealand
    | NoSQL
    | NodeJS
    | Norway
    | Norwegian
    | OCaml
    | OpenSource
    | PHP
    | Philippines
    | PhoneGap
    | Poland
    | Portugal
    | PostgreSQL
    | ProgressiveEnhancement
    | PureScript
    | Python
    | Rails
    | React
    | Remote
    | Romania
    | Ruby
    | Russia
    | Russian
    | SML
    | SVG
    | Scala
    | Scalability
    | Scotland
    | Security
    | Singapore
    | SoftSkills
    | SoftwareCraftsmanship
    | SouthAfrica
    | Spain
    | Sweden
    | Swift
    | Switzerland
    | Testing
    | Tunisia
    | Turkey
    | Turkish
    | UAE
    | USA
    | UX
    | Uruguay
